### ISSUE TITLE
Implement User and Role Management with GitHub IDs

### ISSUE THREAD

**Issue by shah** [tech-by-design/polyglot-prime#15]
We need to implement a user and role management system for our custom application using GitHub IDs. The system should read a configuration file (`oauth2-github-authz.yml`) stored in a private GitHub repository and use this file to manage user access and roles within a Spring Boot 3.3 application. Authentication (AuthN) will be handled by GitHub, while authorization (AuthZ) will be managed using Spring Authorization.

- [x] Integrate User Profile picture in UI.
- [x] Read user and role information from a YAML file in a private GitHub repository.
- [x] Handle authentication using GitHub OAuth.
- [x] Manage authorization using Spring Authorization.
- [x] Disable login requirements and simulate a specific user and role in a local environment.

Consider the following dependencies for the `pom.xml` file:

- GitHub API: [org.kohsuke:github-api](https://mvnrepository.com/artifact/org.kohsuke/github-api)
- Jackson YAML: [com.fasterxml.jackson.dataformat:jackson-dataformat-yaml](https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml)
- Spring OAuth2 Client: [org.springframework.boot:spring-boot-starter-oauth2-client](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-oauth2-client)
- Spring Security: [org.springframework.boot:spring-boot-starter-security](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-security)
- Spring OAuth2 Resource Server: [org.springframework.security:spring-security-oauth2-resource-server](https://mvnrepository.com/artifact/org.springframework.security/spring-security-oauth2-resource-server)

## Instructions

1. **Create Configuration File**
    - Create a YAML file named `oauth2-github-authz.yml` in the private GitHub repository (`github.com/tech-by-design/infrastructure-prime`).
    - Structure the file as follows:

      ```yaml
      users:
        - gitHubId: johndoe
          name: John Doe
          tenantId: tenant123
          resources:
            sudomain1.techbd.org:
              roles:
                 - ADMIN
                 - USER
            sudomain2.techbd.org:
              roles:
                 - USER
        - gitHubId: janesmith
          name: Jane Smith
          tenantId: tenant456
          resources:
            sudomain1.techbd.org:
              roles:
                 - ADMIN
                 - USER
            sudomain2.techbd.org:
              roles:
                 - USER
        - gitHubId: bobjohnson
          name: Bob Johnson
          tenantId: tenant789
          resources:
            sudomain1.techbd.org:
              roles:
                 - DEVELOPER
            sudomain2.techbd.org:
              roles:
                 - ADMIN
      ```

2. **Read YAML File from GitHub**
    - Use the [GitHub API](https://github-api.kohsuke.org/) to access the YAML file from the repository.
    - Use Jackson to parse the YAML content. Refer to the [Jackson Dataformat YAML](https://github.com/FasterXML/jackson-dataformats-text/tree/master/yaml) documentation for details on how to configure and use Jackson for YAML parsing.

3. **Implement GitHub File Reader**
    - Create a Java class to read the file content and parse the YAML data. Use the GitHub API to authenticate and fetch the file.
    - Use Jackson to map the YAML data to a Java object. Follow the [Jackson Documentation](https://github.com/FasterXML/jackson) for detailed instructions on how to configure and use the library.

4. **Configure Spring Security**
    - Set up Spring Security to use GitHub OAuth for authentication. Follow the [Spring Security OAuth2 Client Documentation](https://docs.spring.io/spring-security/reference/reactive/oauth2/client/index.html) for detailed configuration steps.
    - Configure Spring Security to use JWT for resource server authentication. Refer to the [Spring Security OAuth2 Resource Server Documentation](https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/index.html).

5. **Local Environment Configuration**
    - Modify the Spring Security configuration to disable login requirements and simulate a specific user and role when running in a local environment. Check the [Spring Boot Profiles Documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.profiles) for instructions on how to manage different profiles.
    - Create a configuration class to define user details for the local environment.

6. **Service to Manage Users and Roles**
    - Create a service to load and manage user data. Use the service to read the YAML file from GitHub and map the data to Java objects.
    - Implement methods to fetch user details based on roles.

## References and Useful Links

- [GitHub API for Java](https://github-api.kohsuke.org/)
- [Jackson Dataformat YAML](https://github.com/FasterXML/jackson-dataformats-text/tree/master/yaml)
- [Spring Security OAuth2 Client Documentation](https://docs.spring.io/spring-security/reference/reactive/oauth2/client/index.html)
- [Spring Security OAuth2 Resource Server Documentation](https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/index.html)
- [Spring Boot Profiles Documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.profiles)
- [Spring Security Documentation](https://docs.spring.io/spring-security/reference/index.html)
- [Spring Boot Documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/)

## Additional Notes

- Use only environment variables for handling and securing sensitive information, such as GitHub tokens and configuration files.
